version: '3.4'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes: 
        - ./frontend:/app/frontend
    image: fronted:v1.0.0
    ports:
      - $REACT_PORT:$REACT_DOCKER_PORT
    networks:
      - app-network
    depends_on:
      - api
  nginx_proxy:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: proxy:v1.0.0
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_NGINX_PORT
    depends_on:
      - api
      
  api:
    env_file: ./local.env
    environment:
    -  NODE_ENV=$NODE_ENV
    -  PORT=$PORT
    -  MONGO_URL=$MONGO_URL
    -  JWT_TOKEN_SECRET=$JWT_TOKEN_SECRET
    -  PAYPAL_CLIENT_ID=$PAYPAL_CLIENT_ID
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: api:v1.0.0
    container_name: api
    restart: unless-stopped
    volumes:
    - ./backend:/app/backend
    networks:
      - app-network

networks:
  app-network:
     driver: bridge

 
      
  

