version: '3.4'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes: 
        - ./frontend:/app/frontend
    image: fronted:v1.0.0
    ports:
      - "3001:3000"
    networks:
      - app-network
    depends_on:
      - api
  nginx_proxy:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: proxy:v1.0.0
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    ports:
      - "5000:9080"
    depends_on:
      - api
      
  api:
    environment:
    -  NODE_ENV=development
    -  PORT=5000
    -  MONGO_URL=mongodb+srv://produce:produce@produce.yiddo.mongodb.net/products?retryWrites=true
    -  JWT_TOKEN_SECRET=jwt-secret-KEDNEI-RKGRKNG4455
    -  PAYPAL_CLIENT_ID=Adl4GOj_aMNPuVrnolvwBPj9ydP5a0vrOKaEUIopHC9iYdy3sHpqkqb0i0Q9nUhF9JGos5zw7XDOeC0w
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: api:v1.0.0
    container_name: api
    restart: unless-stopped
    volumes:
    - ./backend:/app/backend
    networks:
      - app-network

networks:
  app-network:
     driver: bridge

 
      
  

