version: '3.3'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes: 
        - ./frontend:/app/frontend
    image: fronted:v1.0.0
    ports:
      - "3000:80"
 
      
  

