version: '3.4'

services:
  frontend:
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes: 
        - ./frontend:/app/frontend
    image: 'rayan147/frontend'
    ports:
      - '8080:80'
    
    networks:
      - app-network
    depends_on:
      - api
  redis:
    image: 'redis'
    user: root
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - ./redis/conf:/usr/local/etc/redis
    networks:
      - app-network 
 

  nginx_proxy:
    restart: always
    image: 'rayan147/nginx:latest'
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    ports:
      - '80:80'
   
  
     
  api:
    env_file:
      - ./variables.env
    image: 'rayan147/eco-backend-restful-api:latest'
    container_name: api
    restart: always
    volumes:
    - ./backend:/app/backend
    networks:
      - app-network
    ports:
      - '5000:5000'
    depends_on:
       - nginx_proxy
    

  uploadS3:
    environment:
    -  AWS_BUCKET_IMAGES_NAME=$AWS_BUCKET_IMAGES_NAME
    -  AWS_BUCKET_REGION=$AWS_BUCKET_REGION
    -  AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    -  AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    image: 'rayan147/uploads3:latest'
    container_name: uploadS3
    restart: always
    volumes:
    - ./uploadS3:/app/uploadS3
    networks:
      - app-network
    ports:
      - '5001:5001'
    depends_on:
       - nginx_proxy

networks:
  app-network:
     driver: bridge

 
      
  

