version: '3.3'

services:
  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   volumes: 
  #       - ./frontend:/app/frontend
  #   image: fronted:v1.0.0
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - api
  nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: nodejs:v1.0.0
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
     driver: bridge

 
      
  

