version: '3.3'

services:
  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   volumes: 
  #       - ./frontend:/app/frontend
  #   image: fronted:v1.0.0
  #   ports:
  #     - "80:80"
  #   networks:
  #     - app-network
  #   depends_on:
  #     - api
  nginx_proxy:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: proxy:v1.0.0
    container_name: nginx_proxy
    ports:
      - "5000:9080"
    depends_on:
      - api
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: api:v1.0.0
    container_name: api
    restart: unless-stopped
    volumes:
    - ./backend:/app/backend
    networks:
      - app-network

networks:
  app-network:
     driver: bridge

 
      
  

