const ADMIN_CONSTANTS ={
ADMIN_USER_DELETE_REQUEST: 'ADMIN_USER_DELETE_REQUEST',
ADMIN_USER_DELETE_SUCCESS: 'ADMIN_USER_DELETE_SUCCESS',
ADMIN_USER_DELETE_FAILURE: 'ADMIN_USER_DELETE_FAILURE',

ADMIN_USER_LIST_REQUEST: 'USER_LIST_REQUEST',
ADMIN_USER_LIST_SUCCESS: 'USER_LIST_SUCCESS',
ADMIN_USER_LIST_FAILURE: 'USER_LIST_FAILURE',
ADMIN_USER_LIST_RESET: 'USER_LIST_RESET',

ADMIN_USER_UPDATE_REQUEST: 'ADMIN_USER_UPDATE_REQUEST',
ADMIN_USER_UPDATE_SUCCESS: 'ADMIN_USER_UPDATE_SUCCESS',
ADMIN_USER_UPDATE_FAILURE: 'ADMIN_USER_UPDATE_FAIL',
ADMIN_USER_UPDATE_RESET: 'ADMIN_USER_UPDATE_RESET',

ADMIN_USER_DETAILS_REQUEST: 'ADMIN_USER_DETAILS_REQUEST',
ADMIN_USER_DETAILS_SUCCESS: 'ADMIN_USER_DETAILS_SUCCESS',
ADMIN_USER_DETAILS_FAILURE: 'ADMIN_USER_DETAILS_FAILURE',
ADMIN_USER_DETAILS_RESET: 'ADMIN_USER_DETAILS_RESET',

}

export default ADMIN_CONSTANTS