const ORDER_STATUS = {
    ORDER_CREATE_SUCCESS: 'ORDER_CREATE_SUCCESS',
    ORDER_CREATE_FAILURE: 'ORDER_CREATE_FAILURE',
    ORDER_CREATE_IN_PROGRESS: 'ORDER_CREATE_IN_PROGRESS',
    ORDER_CREATE_REQUEST_START: 'ORDER_CREATE_REQUEST_START',
    ORDER_CREATE_REQUEST_SUCCESS: 'ORDER_CREATE_REQUEST_SUCCESS',
    ORDER_CREATE_REQUEST_FAILURE: 'ORDER_CREATE_REQUEST_FAILURE',

    ORDER_DETAIL_SUCCESS: 'ORDER_DETAIL_SUCCESS',
    ORDER_DETAIL_FAILURE: 'ORDER_DETAIL_FAILURE',
    ORDER_DETAIL_REQUEST_START: 'ORDER_DETAIL_REQUEST_START',
}
export default ORDER_STATUS;
     