const ORDER_STATUS = {
    ORDER_CREATE_SUCCESS: 'ORDER_CREATE_SUCCESS',
    ORDER_CREATE_FAILURE: 'ORDER_CREATE_FAILURE',
    ORDER_CREATE_IN_PROGRESS: 'ORDER_CREATE_IN_PROGRESS',
    ORDER_CREATE_REQUEST_START: 'ORDER_CREATE_REQUEST_START',
    ORDER_CREATE_REQUEST_SUCCESS: 'ORDER_CREATE_REQUEST_SUCCESS',
    ORDER_CREATE_REQUEST_FAILURE: 'ORDER_CREATE_REQUEST_FAILURE',

    ORDER_DETAILS_SUCCESS: 'ORDER_DETAILS_SUCCESS',
    ORDER_DETAILS_FAILURE: 'ORDER_DETAILS_FAILURE',
    ORDER_DETAILS_REQUEST_START: 'ORDER_DETAILS_REQUEST_START',

    ORDER_PAYMENT_SUCCESS: 'ORDER_PAYMENT_SUCCESS',
    ORDER_PAYMENT_FAILURE: 'ORDER_PAYMENT_FAILURE',
    ORDER_PAYMENT_REQUEST_START: 'ORDER_PAYMENT_REQUEST_START',
    ORDER_PAYMENT_RESET : 'ORDER_PAYMENT_RESET',

    ORDER_USER_LIST_SUCCESS: 'ORDER_USER_LIST_SUCCESS',
    ORDER_USER_LIST_FAILURE: 'ORDER_USER_LIST_FAILURE',
    ORDER_USER_LIST_REQUEST_START: 'ORDER_USER_LIST_REQUEST_START',
    ORDER_USER_LIST_RESET : 'ORDER_USER_LIST_RESET',

    ORDER_DELIVER_REQUEST:'ORDER_DELIVER_REQUEST',
    ORDER_DELIVER_SUCCESS:'ORDER_DELIVER_SUCCESS',
    ORDER_DELIVER_FAILURE:'ORDER_DELIVER_FAILURE',
    ORDER_DELIVER_RESET:'ORDER_DELIVER_RESET',

    ORDER_LIST_SUCCESS :'ORDER_LIST_SUCCESS',
    ORDER_LIST_FAILURE:'ORDER_LIST_FAILURE',
    ORDER_LIST_REQUEST:'ORDER_LIST_REQUEST',


}
export default ORDER_STATUS;
     